In [1]:
import numpy

In [2]:
import numpy as np

In [4]:
a = np.array([[0,6,12,18,24],[32,38,44,50,56],[62,68,74,80,86],[92,98,104,110,116],[122,128,1341,140,146]])

In [5]:
a

array([[   0,    6,   12,   18,   24],
       [  32,   38,   44,   50,   56],
       [  62,   68,   74,   80,   86],
       [  92,   98,  104,  110,  116],
       [ 122,  128, 1341,  140,  146]])

In [10]:
nama_1 = 'supri'
nama_2 = 'yanto'
nama_3 = 'rohadi'
dimensi_1 = len(nama_1)
dimensi_2 = len(nama_2)
step = len(nama_3)
z = np.arange(0,step*dimensi_2,step)
array_placeholder = np.array([])
for i in range(dimensi_1):
    array_placeholder = np.append(array_placeholder,z)

In [11]:
print (z)

[ 0  6 12 18 24]


In [12]:
print (array_placeholder)

[ 0.  6. 12. 18. 24.  0.  6. 12. 18. 24.  0.  6. 12. 18. 24.  0.  6. 12.
 18. 24.  0.  6. 12. 18. 24.]


In [13]:
array_placeholder.reshape(dimensi_1,dimensi_2)

array([[ 0.,  6., 12., 18., 24.],
       [ 0.,  6., 12., 18., 24.],
       [ 0.,  6., 12., 18., 24.],
       [ 0.,  6., 12., 18., 24.],
       [ 0.,  6., 12., 18., 24.]])