In [6]:
import numpy as np

In [2]:
arr1 = [[1,2,3,4],[5,6,7,8]]
arr2 = [[9,10],[11,12],[13,14]]
arr3 = [[15,16,17,18]]

In [7]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[9,10],[11,12],[13,14]])

In [8]:
arr2 = np.append(arr2,arr2[1])

In [9]:
print(arr2)

[ 9 10 11 12 13 14 11 12]


In [10]:
arr2 = arr2.reshape(2,4)

In [11]:
print(arr2)

[[ 9 10 11 12]
 [13 14 11 12]]


In [12]:
arr5 = np.hstack((arr1,arr2))

In [13]:
print(arr5)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 11 12]]
